disable dependencies on wrappers
message to skale:

We were just going through the motions of redeploying in hardhat some wrapper contracts, and I encountered this error. Please see the error message about node synced status.

Our deployment tooling is using HH best practices AFAICT, however this smells like an archive like bug. Can you provide any insight here?

yarn run v1.22.19
$ hardhat deploy --tags WrapTokens --network rubyNewChain
Nothing to compile
No need to generate any newer typings.
reusing "WrapETHC" at 0x201f24e897B0711dCBb21073a6A75F570a73fde4
WETH decimals:  18
WETH name:  Europa Wrapped ETHC
An unexpected error occurred:

Error: ERROR processing /home/jasper/Ruby/backend/deploy/mappedTokens/MappedDAI.ts:
Error: cannot get the transaction for RubyDAI's previous deployment, please check your node synced status.
    at fetchIfDifferent (/home/jasper/Ruby/backend/node_modules/hardhat-deploy/src/helpers.ts:909:17)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async _deployOne (/home/jasper/Ruby/backend/node_modules/hardhat-deploy/src/helpers.ts:932:24)
    at DeploymentsManager.executeDeployScripts (/home/jasper/Ruby/backend/node_modules/hardhat-deploy/src/DeploymentsManager.ts:1223:19)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async DeploymentsManager.runDeploy (/home/jasper/Ruby/backend/node_modules/hardhat-deploy/src/DeploymentsManager.ts:1053:5)
    at async SimpleTaskDefinition.action (/home/jasper/Ruby/backend/node_modules/hardhat-deploy/src/index.ts:409:5)
    at async Environment._runTaskDefinition (/home/jasper/Ruby/backend/node_modules/hardhat/src/internal/core/runtime-environment.ts:217:14)
    at async Environment.run (/home/jasper/Ruby/backend/node_modules/hardhat/src/internal/core/runtime-environment.ts:129:14)
    at async SimpleTaskDefinition.action (/home/jasper/Ruby/backend/node_modules/hardhat-deploy/src/index.ts:555:32)
    at async Environment._runTaskDefinition (/home/jasper/Ruby/backend/node_modules/hardhat/src/internal/core/runtime-environment.ts:217:14)
    at async Environment.run (/home/jasper/Ruby/backend/node_modules/hardhat/src/internal/core/runtime-environment.ts:129:14)
    at async SimpleTaskDefinition.action (/home/jasper/Ruby/backend/node_modules/hardhat-deploy/src/index.ts:640:5)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.